### ISSUE TITLE
npm `subject`

### ISSUE THREAD

**Issue by PatrickJS** [simonfan/subject#1]
do you mind giving up `subject` on npm to be part of RxJS?

**Comment by simonfan** [comment]
@gdi2290 I would not mind at all, but this project is being used in production at a startup I've worked for :/.

I think that changing its name could do lots of harm to that project, sorry!

**Comment by PatrickJS** [comment]
no worries it doesn't look like `observable` on npm will give up their name either since there's a ton of modules being used with it
